### ISSUE TITLE
CSI Failed with Nomad

### ISSUE THREAD

**Issue by fred-gb** [seaweedfs/seaweedfs-csi-driver#169]
Bonjour, 👋🏻 

I think I posted on wrong Seaweed Github issue last time.

https://github.com/seaweedfs/seaweedfs/issues/5664

So, I post again here.

I upgrade to 3.68 today, but when I launch Nomad job example, same error
```
failed to setup alloc: pre-run hook "csi_hook" failed: mounting volumes: rpc error: code = Unavailable desc = error reading from server: EOF
```

And on `seaweed-csi` job:
```


I0620 07:39:36.430066 main.go:73 will run node: true, controller: true, attacher: true
I0620 07:39:36.430327 main.go:79 connect to filer 172.17.0.1:8888
I0620 07:39:36.430368 driver.go:53 Driver: seaweedfs-csi-driver version: 1.0.0
I0620 07:39:36.430795 driver.go:127 Enabling volume access mode: MULTI_NODE_MULTI_WRITER
I0620 07:39:36.430799 driver.go:127 Enabling volume access mode: SINGLE_NODE_WRITER
I0620 07:39:36.430801 driver.go:127 Enabling volume access mode: SINGLE_NODE_MULTI_WRITER
I0620 07:39:36.430802 driver.go:127 Enabling volume access mode: SINGLE_NODE_SINGLE_WRITER
I0620 07:39:36.430808 driver.go:134 Enabling controller service capability: CREATE_DELETE_VOLUME
I0620 07:39:36.430811 driver.go:134 Enabling controller service capability: SINGLE_NODE_MULTI_WRITER
I0620 07:39:36.430812 driver.go:134 Enabling controller service capability: EXPAND_VOLUME
I0620 07:39:36.430813 driver.go:134 Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0620 07:39:36.430815 driver.go:90 starting
I0620 07:39:36.432220 server.go:92 Listening for connections on address: &net.UnixAddr{Name:"/csi/csi.sock", Net:"unix"}
I0620 07:58:18.099556 controllerserver.go:112 controller unpublish volume req: example-seaweedfs-volume
I0620 07:58:48.113156 controllerserver.go:112 controller unpublish volume req: example-seaweedfs-volume
I0620 07:59:29.224755 nodeserver.go:34 node stage volume example-seaweedfs-volume to /local/csi/staging/default/example-seaweedfs-volume/rw-file-system-multi-node-multi-writer
I0620 07:59:29.225425 mounter_seaweedfs.go:45 mounting [172.17.0.1:8888] /buckets/example-seaweedfs-volume to /local/csi/staging/default/example-seaweedfs-volume/rw-file-system-multi-node-multi-writer
I0620 07:59:29.226315 mounter.go:53 Mounting fuse with command: weed and args: [-logtostderr=true mount -dirAutoCreate=true -umask=000 -dir=/local/csi/staging/default/example-seaweedfs-volume/rw-file-system-multi-node-multi-writer -localSocket=/tmp/seaweedfs-mount-1892693304.sock -cacheDir=/local/cache_dir/example-seaweedfs-volume -cacheCapacityMB=256 -filer=172.17.0.1:8888 -filer.path=/buckets/example-seaweedfs-volume -concurrentWriters=32 -collection=example-seaweedfs-volume]
I0620 07:59:29.535794 needle_map_leveldb.go:122 generateLevelDbFile /local/cache_dir/example-seaweedfs-volume/dc68c46c/c0_2_0.ldb, watermark 0, num of entries:0
I0620 07:59:29.556232 needle_map_leveldb.go:66 Loading /local/cache_dir/example-seaweedfs-volume/dc68c46c/c0_2_0.ldb... , watermark: 0
I0620 07:59:29.561160 needle_map_leveldb.go:122 generateLevelDbFile /local/cache_dir/example-seaweedfs-volume/dc68c46c/c0_2_1.ldb, watermark 0, num of entries:0
I0620 07:59:29.570657 needle_map_leveldb.go:66 Loading /local/cache_dir/example-seaweedfs-volume/dc68c46c/c0_2_1.ldb... , watermark: 0
I0620 07:59:29.580955 needle_map_leveldb.go:122 generateLevelDbFile /local/cache_dir/example-seaweedfs-volume/dc68c46c/c1_3_0.ldb, watermark 0, num of entries:0
I0620 07:59:29.590132 needle_map_leveldb.go:66 Loading /local/cache_dir/example-seaweedfs-volume/dc68c46c/c1_3_0.ldb... , watermark: 0
I0620 07:59:29.599698 needle_map_leveldb.go:122 generateLevelDbFile /local/cache_dir/example-seaweedfs-volume/dc68c46c/c1_3_1.ldb, watermark 0, num of entries:0
I0620 07:59:29.607605 needle_map_leveldb.go:66 Loading /local/cache_dir/example-seaweedfs-volume/dc68c46c/c1_3_1.ldb... , watermark: 0
I0620 07:59:29.614112 needle_map_leveldb.go:122 generateLevelDbFile /local/cache_dir/example-seaweedfs-volume/dc68c46c/c1_3_2.ldb, watermark 0, num of entries:0
I0620 07:59:29.621896 needle_map_leveldb.go:66 Loading /local/cache_dir/example-seaweedfs-volume/dc68c46c/c1_3_2.ldb... , watermark: 0
I0620 07:59:29.626987 needle_map_leveldb.go:122 generateLevelDbFile /local/cache_dir/example-seaweedfs-volume/dc68c46c/c2_2_0.ldb, watermark 0, num of entries:0
I0620 07:59:29.636153 needle_map_leveldb.go:66 Loading /local/cache_dir/example-seaweedfs-volume/dc68c46c/c2_2_0.ldb... , watermark: 0
I0620 07:59:29.643501 needle_map_leveldb.go:122 generateLevelDbFile /local/cache_dir/example-seaweedfs-volume/dc68c46c/c2_2_1.ldb, watermark 0, num of entries:0
I0620 07:59:29.652967 needle_map_leveldb.go:66 Loading /local/cache_dir/example-seaweedfs-volume/dc68c46c/c2_2_1.ldb... , watermark: 0
I0620 07:59:29.654415 leveldb_store.go:47 filer store dir: /local/cache_dir/example-seaweedfs-volume/dc68c46c/meta
I0620 07:59:29.654446 file_util.go:27 Folder /local/cache_dir/example-seaweedfs-volume/dc68c46c/meta Permission: -rwxr-xr-x
I0620 07:59:29.707694 mount_std.go:268 mounted 172.17.0.1:8888/buckets/example-seaweedfs-volume to /local/csi/staging/default/example-seaweedfs-volume/rw-file-system-multi-node-multi-writer
I0620 07:59:29.707837 mount_std.go:269 This is SeaweedFS version 30GB 3.62  linux arm64
panic: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

goroutine 276 [running]:
github.com/seaweedfs/seaweedfs-csi-driver/pkg/k8s.NewInCluster()
	/go/src/github.com/seaweedfs/seaweedfs-csi-driver/pkg/k8s/client.go:16 +0x7c
github.com/seaweedfs/seaweedfs-csi-driver/pkg/k8s.GetVolumeCapacity({0x40001be8e8, 0x18})
	/go/src/github.com/seaweedfs/seaweedfs-csi-driver/pkg/k8s/client.go:28 +0x38
github.com/seaweedfs/seaweedfs-csi-driver/pkg/driver.(*NodeServer).NodeStageVolume(0x400037dfb0, {0x1067808?, 0x10?}, 0x4000269200)
	/go/src/github.com/seaweedfs/seaweedfs-csi-driver/pkg/driver/nodeserver.go:84 +0xae8
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeStageVolume_Handler.func1({0x168c488, 0x40003fcea0}, {0x13341c0?, 0x4000269200})
	/go/pkg/mod/github.com/container-storage-interface/spec@v1.8.0/lib/go/csi/csi.pb.go:7034 +0x74
github.com/seaweedfs/seaweedfs-csi-driver/pkg/driver.logGRPC({0x168c488, 0x40003fcea0}, {0x13341c0?, 0x4000269200?}, 0x400044ee80, 0x40003a17a0)
	/go/src/github.com/seaweedfs/seaweedfs-csi-driver/pkg/driver/utils.go:64 +0xd4
github.com/container-storage-interface/spec/lib/go/csi._Node_NodeStageVolume_Handler({0x130d680?, 0x400037dfb0}, {0x168c488, 0x40003fcea0}, 0x400019b500, 0x1503a10)
	/go/pkg/mod/github.com/container-storage-interface/spec@v1.8.0/lib/go/csi/csi.pb.go:7036 +0x12c
google.golang.org/grpc.(*Server).processUnaryRPC(0x400046a000, {0x16924b8, 0x400048d040}, 0x40002dafc0, 0x400026e810, 0x22e5040, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.57.1/server.go:1358 +0xc04
google.golang.org/grpc.(*Server).handleStream(0x400046a000, {0x16924b8, 0x400048d040}, 0x40002dafc0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.57.1/server.go:1735 +0x7cc
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/go/pkg/mod/google.golang.org/grpc@v1.57.1/server.go:970 +0xb4
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 66
	/go/pkg/mod/google.golang.org/grpc@v1.57.1/server.go:981 +0x160
```

I find this issue: https://github.com/seaweedfs/seaweedfs-csi-driver/issues/147

Is it similar?

How I can use lastest version of CSI docker image? If needed.

UI show this, is it enough for "fews" volumes:
![Capture d’écran 2024-06-20 à 10 21 46](https://github.com/seaweedfs/seaweedfs-csi-driver/assets/17061623/0efbe911-5043-4a44-afd6-5412c269f237)

Thanks!

**Comment by chrislusf** [comment]
@duanhongyi ^^

**Comment by chrislusf** [comment]
Added a fix.

**Comment by fred-gb** [comment]
Thanks @chrislusf , but on https://hub.docker.com/r/chrislusf/seaweedfs-csi-driver/tags

Last pushed 5 months ago by [chrislusf](https://hub.docker.com/u/chrislusf)
